export interface Product {
  id: string
  name: string
  price: number
  category: "men" | "women" | "accessories"
  image: string
  image_gallery?: string[]
  shortDescription: string
  fullDescription: string
  sizes: string[]
  rating: number
  isNew?: boolean
}

export const products: Product[] = [
  // Men's Collection
  {
    id: "m001",
    name: "Classic Indigo Corduroy Utility Jacket",
    price: 189,
    category: "men",
    image: "/Classic-Jacket1.jpg",
    image_gallery: [
      "/Classic-Jacket2.jpg",
      "/Classic-Jacket3.jpg",
      "/Classic-Jacket4.jpg",
      "/Classic-Jacket5.jpg",
    ],
    shortDescription: "Classic indigo jacket crafted from premium cotton corduroy",
    fullDescription:
      "This classic indigo corduroy utility jacket is made from premium cotton for lasting comfort and durability. Featuring a timeless workwear design with reinforced seams, functional pockets, and a relaxed fit, it pairs effortlessly with casual or smart outfits. Suitable for year-round wear.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "m002",
    name: "Performance Quick-Dry Short Sleeve Golf Polo for Men",
    price: 89,
    category: "men",
    image: "/Cotton-Polo-Shirt1.jpg",
    image_gallery: [
      "/Cotton-Polo-Shirt1.jpg",
      "/Cotton-Polo-Shirt2.jpg",
      "/Cotton-Polo-Shirt3.jpg",
    ],
    shortDescription: "Lightweight men’s golf polo with quick-dry and moisture-wicking fabric",
    fullDescription:
      "This performance men’s golf polo is crafted from breathable, moisture-wicking fabric that keeps you cool and dry on and off the course. Designed with a classic short sleeve silhouette, it offers lightweight comfort, quick-dry functionality, and versatile style for both casual wear and sports activities.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "m003",
    name: "Vintage American Graphic Tee",
    price: 65,
    category: "men",
    image: "/Touch-Grass-Tshirt1.jpg",
    image_gallery: [
      "/Touch-Grass-Tshirt1.jpg",
      "/Touch-Grass-Tshirt2.jpg",
      "/Touch-Grass-Tshirt3.jpg",
      "/Touch-Grass-Tshirt4.jpg",
      "/Touch-Grass-Tshirt1.jpg",
    ],
    shortDescription: "Authentic vintage-inspired graphic tee with American heritage design",
    fullDescription:
      "Celebrate American heritage with this vintage-inspired graphic tee. Made from soft cotton blend with distressed printing for an authentic worn-in look. Features classic American motifs and comfortable regular fit. Made in the USA.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
  },
  {
    id: "m004",
    name: "Leather Work Boots",
    price: 299,
    category: "men",
    image: "/Athletic-boots1.jpg",
    image_gallery: [
      "/Athletic-boots1.jpg",
      "/Athletic-boots2.jpg",
      "/Athletic-boots3.jpg",
      "/Athletic-boots4.jpg",
      "/Athletic-boots1.jpg",
    ],
    shortDescription: "Durable athletic Chelsea boots designed for comfort and performance",
    fullDescription:
      "These men's Chelsea boots feature a soft toe design and are crafted with breathable, high-quality materials for all-day comfort. Built with a flexible sole and easy slip-on style, they are ideal for both casual wear and active use..",
    sizes: ["7", "8", "9", "10", "11", "12", "13", "14" , "15"],
    rating: 4.9,
  },
  {
    id: "m005",
    name: "Flannel Button-Down Shirt",
    price: 125,
    category: "men",
    image: "/mens-flannel-shirt.png",
    shortDescription: "Warm flannel shirt in classic American plaid patterns",
    fullDescription:
      "Stay warm in style with this premium flannel shirt. Made from 100% cotton flannel with classic American plaid patterns. Features button-down collar, chest pocket, and relaxed fit for comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
  },
  {
    id: "m006",
    name: "Athletic Performance Shorts",
    price: 75,
    category: "men",
    image: "/mens-athletic-shorts-performance.png",
    shortDescription: "High-performance athletic shorts for active lifestyle",
    fullDescription:
      "Designed for peak performance, these athletic shorts feature moisture-wicking fabric, four-way stretch, and secure zip pockets. Perfect for workouts, running, or casual wear. Made with American athletic wear technology.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
  },
  {
    id: "m007",
    name: "Premium 5.6 oz United Athle Cotton Tee",
    price: 75,
    category: "men",
    image: "/Athle-Cotton-Tee1.jpg",
    image_gallery: [
      "/Athle-Cotton-Tee2.jpg",
      "/Athle-Cotton-Tee3.jpg",
      "/Athle-Cotton-Tee4.jpg",
      "/Athle-Cotton-Tee1.jpg",
    ],
    shortDescription: "Soft and durable 5.6 oz cotton t-shirt with superior quality",
    fullDescription:
      "This premium 5.6 oz United Athle t-shirt is crafted from high-quality cotton, delivering exceptional softness and durability. Its classic fit and breathable fabric make it ideal for everyday wear, ensuring comfort and long-lasting performance.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
  },
  {
    id: "m008",
    name: "Men’s Cotton Linen Long Sleeve Henley Beach Shirt",
    price: 120,
    category: "men",
    image: "/Henley-shirt1.jpg",
    image_gallery: [
      "/Henley-shirt2.jpg",
      "/Henley-shirt3.jpg",
      "/Henley-shirt4.jpg",
      "/Henley-shirt5.jpg",
      "/Henley-shirt6.jpg",
    ],
    shortDescription: "Breathable cotton-linen Henley shirt with long sleeves for relaxed style",
    fullDescription:
      "This men’s cotton-linen Henley shirt offers lightweight breathability and a soft, natural feel. Featuring a classic long sleeve design with a buttoned placket, it’s perfect for casual outings, beach days, or relaxed weekend wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
  },
  {
    id: "m009",
    name: "Men’s 2-Piece Floral Graphic Button-Up Shirt and Shorts Set",
    price: 120,
    category: "men",
    image: "/Floral Graphic2.jpg",
    image_gallery: [
      "/Floral Graphic2.jpg",
      "/Floral Graphic3.jpg",
      "/Floral Graphic4.jpg",
      "/Floral Graphic1.jpg",
    ],
    shortDescription: "Casual two-piece set with floral graphic shirt and matching shorts",
    fullDescription:
      "This men’s two-piece summer set includes a short sleeve button-up shirt with vibrant floral and letter graphics, paired with matching shorts for a coordinated look. Made from lightweight, breathable fabric, it’s perfect for beach days, vacations, and casual outings.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
  },
  {
    id: "m010",
    name: "Men’s Lightweight Quick-Dry Athletic Shorts",
    price: 120,
    category: "men",
    image: "/Lightweight Quick-Dr1.jpg",
    image_gallery: [
      "/Lightweight Quick-Dr2.jpg",
      "/Lightweight Quick-Dr3.jpg",
      "/Lightweight Quick-Dr4.jpg",
      "/Lightweight Quick-Dr5.jpg",
    ],
    shortDescription: "Breathable quick-dry athletic shorts for running, gym, and outdoor sports",
    fullDescription:
      "These men’s lightweight athletic shorts are designed for maximum comfort and performance. Made with quick-dry, breathable fabric, they feature an adjustable waistband and versatile length options, making them ideal for running, gym workouts, basketball, tennis, hiking, and other active pursuits.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
  },
  {
    id: "m011",
    name: "Casual Cotton Crewneck T-Shirt",
    price: 22,
    category: "men",
    image: "/Casual-Cotton1.jpg",
    image_gallery: [
      "/Casual-Cotton1.jpg",
      "/Casual-Cotton2.jpg",
      "/Casual-Cotton3.jpg",
      "/Casual-Cotton4.jpg",
      "/Casual-Cotton5.jpg",
      "/Casual-Cotton6.jpg",
    ],
    shortDescription: "Soft cotton T-shirt with a relaxed crewneck fit",
    fullDescription:
      "This casual cotton crewneck T-shirt is made from breathable cotton jersey, offering everyday comfort with a relaxed fit. Perfect for layering or wearing on its own.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    isNew: true,
  },
  {
    id: "m012",
    name: "Slim Fit Stretch Chinos",
    price: 48,
    category: "men",
    image: "/Slim-Chinos1.jpg",
    image_gallery: [
      "/Slim-Chinos2.jpg",
      "/Slim-Chinos3.jpg",
      "/Slim-Chinos4.jpg",
      "/Slim-Chinos5.jpg",
      "/Slim-Chinos6.jpg",
    ],
    shortDescription: "Versatile slim-fit chinos with stretch comfort",
    fullDescription:
      "Crafted from a cotton-blend fabric with a touch of stretch, these slim-fit chinos provide comfort and flexibility. Ideal for casual outings or smart-casual occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    isNew: false,
  },
  {
    id: "m013",
    name: "Lightweight Zip-Up Hoodie",
    price: 39,
    category: "men",
    image: "/ZipHoodie1.jpg",
    image_gallery: [
      "/ZipHoodie2.jpg",
      "/ZipHoodie3.jpg",
      "/ZipHoodie4.jpg",
      "/ZipHoodie5.jpg",
    ],
    shortDescription: "Everyday hoodie with zip closure and adjustable hood",
    fullDescription:
      "A lightweight hoodie featuring a full front zipper, adjustable drawstring hood, and side pockets. Made from soft cotton-blend fabric for comfort during daily wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
    isNew: true,
  },
  {
    id: "m014",
    name: "Classic Linen Short-Sleeve Shirt",
    price: 45,
    category: "men",
    image: "/Linen-Short-Sleeve4.jpg",
    image_gallery: [
      "/Linen-Short-Sleeve1.jpg",
      "/Linen-Short-Sleeve2.png",
      "/Linen-Short-Sleeve3.jpg",
      "/Linen-Short-Sleeve4.jpg",
      "/Linen-Short-Sleeve5.jpg",
      "/Linen-Short-Sleeve6.jpg",
      "/Linen-Short-Sleeve7.jpg",
    ],
    shortDescription: "Breathable linen shirt with short sleeves",
    fullDescription:
      "This classic linen short-sleeve shirt is lightweight and breathable, making it perfect for warm weather. Designed with a button-down front and a relaxed fit for casual style.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    isNew: false,
  },
  {
    id: "m015",
    name: "Everyday Straight-Leg Jeans",
    price: 55,
    category: "men",
    image: "/Straight-Leg-Jeans1.jpg",
    image_gallery: [
      "/Straight-Leg-Jeans1.jpg",
      "/Straight-Leg-Jeans2.jpg",
      "/Straight-Leg-Jeans3.jpg",
      "/Straight-Leg-Jeans4.jpg",
      "/Straight-Leg-Jeans5.jpg",
      "/Straight-Leg-Jeans6.jpg",
    ],
    shortDescription: "Durable straight-leg jeans for daily wear",
    fullDescription:
      "These everyday straight-leg jeans are made from durable cotton denim with a regular fit. A versatile piece that pairs well with T-shirts, shirts, or jackets.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "m016",
    name: "Padded Winter Jacket",
    price: 98,
    category: "men",
    image: "/WinterJacket1.webp",
    image_gallery: [
      "/WinterJacket2.webp",
      "/WinterJacket3.webp",
      "/WinterJacket4.webp",
      "/WinterJacket5.webp",
      "/WinterJacket6.webp",
    ],
    shortDescription: "Warm padded jacket for cold weather",
    fullDescription:
      "This padded winter jacket is insulated with synthetic fill for warmth and features a water-resistant shell. Equipped with zip pockets and a high collar for extra protection.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "m017",
    name: "Casual Polo Shirt",
    price: 32,
    category: "men",
    image: "/Casual-Polo-Shirt1.jpg",
    image_gallery: [
      "/Casual-Polo-Shirt1.jpg",
      "/Casual-Polo-Shirt2.jpg",
      "/Casual-Polo-Shirt3.jpg",
      "/Casual-Polo-Shirt4.jpg",
    ],
    shortDescription: "Cotton polo shirt with a modern slim fit",
    fullDescription:
      "A timeless casual polo shirt designed with a soft collar, button placket, and short sleeves. Made from breathable cotton fabric for comfort and style.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "m018",
    name: "Relaxed Fit Cargo Pants",
    price: 52,
    category: "men",
    image: "/CargoPants1.jpg",
    image_gallery: [
      "/CargoPants2.jpg",
      "/CargoPants3.jpg",
      "/CargoPants4.jpg",
      "/CargoPants5.jpg",
    ],
    shortDescription: "Functional cargo pants with multiple pockets",
    fullDescription:
      "These relaxed-fit cargo pants are designed for both comfort and utility. Featuring multiple pockets, adjustable waistband, and durable cotton-blend fabric.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    isNew: false,
  },
  {
    id: "m019",
    name: "Knitted Crewneck Sweater",
    price: 49,
    category: "men",
    image: "/Knitted-Sweater1.jpg",
    image_gallery: [
      "/Knitted-Sweater2.jpg",
      "/Knitted-Sweater3.jpg",
      "/Knitted-Sweater4.jpg",
      "/Knitted-Sweater5.jpg",
      "/Knitted-Sweater6.jpg",
    ],
    shortDescription: "Cozy knitted sweater for cooler days",
    fullDescription:
      "A knitted crewneck sweater made from soft acrylic blend yarn. Provides warmth and comfort while maintaining a classic, versatile style for casual wear.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    isNew: true,
  },
  {
    id: "m020",
    name: "Lightweight Windbreaker Jacket",
    price: 64,
    category: "men",
    image: "/Windbreaker1.jpg",
    image_gallery: [
      "/Windbreaker2.jpg",
      "/Windbreaker3.jpg",
      "/Windbreaker4.jpg",
      "/Windbreaker5.jpg",
    ],
    shortDescription: "Wind-resistant jacket for transitional weather",
    fullDescription:
      "This lightweight windbreaker jacket is made from water-repellent fabric to provide protection against wind and light rain. Features a zip closure and elastic cuffs for a secure fit.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    isNew: false,
  },
  {
    id: "m021",
    name: "Basic V-Neck T-Shirt",
    price: 20,
    category: "men",
    image: "/Vneck-Tshirt1.jpg",
    image_gallery: [
      "/Vneck-Tshirt2.jpg",
      "/Vneck-Tshirt3.jpg",
      "/Vneck-Tshirt4.jpg",
      "/Vneck-Tshirt5.jpg",
    ],
    shortDescription: "Soft cotton V-neck T-shirt with a modern cut",
    fullDescription:
      "This basic V-neck T-shirt is crafted from breathable cotton fabric, offering a slim yet comfortable fit. Ideal for layering or wearing casually in warmer seasons.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    isNew: true,
  },
  {
    id: "m022",
    name: "Casual Button-Up Shirt",
    price: 42,
    category: "men",
    image: "/Casual-Shirt1.jpg",
    image_gallery: [
      "/Casual-Shirt2.jpg",
      "/Casual-Shirt3.jpg",
      "/Casual-Shirt4.jpg",
      "/Casual-Shirt5.jpg",
    ],
    shortDescription: "Lightweight cotton button-up shirt with long sleeves",
    fullDescription:
      "A casual button-up shirt designed with a relaxed fit and lightweight fabric. Perfect for both work and casual settings, offering comfort and easy style.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "m023",
    name: "Slim Fit Jogger Pants",
    price: 46,
    category: "men",
    image: "/Jogger-Pants1.jpg",
    image_gallery: [
      "/Jogger-Pants2.jpg",
      "/Jogger-Pants3.jpg",
      "/Jogger-Pants4.jpg",
      "/Jogger-Pants5.jpg",
      "/Jogger-Pants6.jpg",
    ],
    shortDescription: "Comfortable jogger pants with tapered legs",
    fullDescription:
      "These slim fit jogger pants are made from a cotton-blend fabric with elastic cuffs and waistband. Designed for both casual wear and light workouts.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "m024",
    name: "Light Knit Cardigan",
    price: 58,
    category: "men",
    image: "/Cardigan1.jpg",
    image_gallery: [
      "/Cardigan2.jpg",
      "/Cardigan3.jpg",
      "/Cardigan4.jpg",
      "/Cardigan5.jpg",
    ],
    shortDescription: "Classic cardigan with button closure",
    fullDescription:
      "This light knit cardigan is a versatile layering piece. Features a button-up front, ribbed cuffs, and a comfortable fit suitable for everyday wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    isNew: false,
  },
  {
    id: "m025",
    name: "Everyday Crew Socks (3-Pack)",
    price: 18,
    category: "men",
    image: "/Crew-Socks1.jpg",
    image_gallery: [
      "/Crew-Socks2.jpg",
      "/Crew-Socks3.jpg",
      "/Crew-Socks4.jpg",
      "/Crew-Socks5.jpg",
      "/Crew-Socks6.jpg",
    ],
    shortDescription: "Soft cotton crew socks, pack of three pairs",
    fullDescription:
      "These everyday crew socks are made from breathable cotton blend for comfort and durability. Designed to fit snugly and suitable for all-day wear.",
    sizes: ["M", "L", "XL"],
    rating: 4.3,
    isNew: true,
  },
  {
    id: "m026",
    name: "Casual Summer Shorts",
    price: 34,
    category: "men",
    image: "/Summer-Shorts1.jpg",
    image_gallery: [
      "/Summer-Shorts2.jpg",
      "/Summer-Shorts3.jpg",
      "/Summer-Shorts4.jpg",
      "/Summer-Shorts5.jpg",
      "/Summer-Shorts6.jpg",
    ],
    shortDescription: "Lightweight cotton shorts with side pockets",
    fullDescription:
      "Designed for warm days, these casual summer shorts feature an elastic waistband with drawstring and multiple pockets. Made from breathable cotton fabric.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "m027",
    name: "Long-Sleeve Henley Shirt",
    price: 38,
    category: "men",
    image: "/Henley-Shirts1.jpg",
    image_gallery: [
      "/Henley-Shirts2.jpg",
      "/Henley-Shirts3.jpg",
      "/Henley-Shirts4.jpg",
      "/Henley-Shirts5.jpg",
      "/Henley-Shirts6.jpg",
      "/Henley-Shirts7.jpg",
    ],
    shortDescription: "Classic henley shirt with button placket",
    fullDescription:
      "This long-sleeve henley shirt is made from soft cotton-blend fabric. Featuring a three-button placket and a relaxed fit, it’s great for layering or casual wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "m028",
    name: "Basic Pullover Sweatshirt",
    price: 44,
    category: "men",
    image: "/Pullover-Sweatshirt1.jpg",
    image_gallery: [
      "/Pullover-Sweatshirt2.jpg",
      "/Pullover-Sweatshirt3.jpg",
      "/Pullover-Sweatshirt4.jpg",
      "/Pullover-Sweatshirt5.jpg",
      "/Pullover-Sweatshirt6.jpg",
    ],
    shortDescription: "Simple crewneck sweatshirt for daily wear",
    fullDescription:
      "This basic pullover sweatshirt is crafted from cotton-blend fleece, providing comfort and warmth. A timeless crewneck design suitable for casual outfits.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "m029",
    name: "Relaxed Fit Flannel Shirt",
    price: 52,
    category: "men",
    image: "/Flannel-Shirt1.jpg",
    image_gallery: [
      "/Flannel-Shirt2.jpg",
      "/Flannel-Shirt3.jpg",
      "/Flannel-Shirt4.jpg",
      "/Flannel-Shirt5.jpg",
      "/Flannel-Shirt6.jpg",
    ],
    shortDescription: "Soft flannel shirt with checkered pattern",
    fullDescription:
      "A relaxed-fit flannel shirt made from soft brushed cotton. Designed with long sleeves, button closure, and a classic checkered style for casual looks.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    isNew: true,
  },
  {
    id: "m030",
    name: "Lightweight Sleeveless Tank Top",
    price: 19,
    category: "men",
    image: "/Tank-Top1.jpg",
    image_gallery: [
      "/Tank-Top2.jpg",
      "/Tank-Top3.jpg",
      "/Tank-Top4.jpg",
      "/Tank-Top5.jpg",
    ],
    shortDescription: "Breathable cotton tank top for casual wear",
    fullDescription:
      "This sleeveless tank top is designed for comfort in hot weather. Made from breathable cotton fabric, it’s ideal for workouts, lounging, or casual summer style.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
    isNew: true,
  },
  {
    id: "m031",
    name: "Relaxed Fit Linen Trousers",
    price: 56,
    category: "men",
    image: "/Linen-Trousers1.jpg",
    image_gallery: [
      "/Linen-Trousers2.jpg",
      "/Linen-Trousers3.jpg",
      "/Linen-Trousers4.jpg",
      "/Linen-Trousers5.jpg",
    ],
    shortDescription: "Breathable linen trousers with a relaxed fit",
    fullDescription:
      "These relaxed fit linen trousers are lightweight and breathable, perfect for warm weather. Designed with a drawstring waist and straight-leg cut for casual comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "m032",
    name: "Knitted Half-Zip Sweater",
    price: 62,
    category: "men",
    image: "/HalfZip-Sweater1.jpg",
    image_gallery: [
      "/HalfZip-Sweater2.jpg",
      "/HalfZip-Sweater3.jpg",
      "/HalfZip-Sweater4.jpg",
      "/HalfZip-Sweater5.jpg",
      "/HalfZip-Sweater6.jpg",
    ],
    shortDescription: "Cozy knitted sweater with half-zip design",
    fullDescription:
      "A knitted sweater featuring a half-zip collar for versatile styling. Made from soft blended yarn to provide warmth and comfort in cooler weather.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    isNew: false,
  },
  {
    id: "m033",
    name: "Casual Drawstring Hoodie",
    price: 40,
    category: "men",
    image: "/Drawstring-Hoodie1.jpg",
    image_gallery: [
      "/Drawstring-Hoodie2.jpg",
      "/Drawstring-Hoodie3.jpg",
      "/Drawstring-Hoodie4.jpg",
      "/Drawstring-Hoodie5.jpg",
      "/Drawstring-Hoodie6.jpg",
    ],
    shortDescription: "Everyday hoodie with adjustable drawstring hood",
    fullDescription:
      "This casual hoodie is made from a cotton-poly blend for softness and durability. Features ribbed cuffs, kangaroo pocket, and a drawstring hood for added comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    isNew: true,
  },
  {
    id: "m034",
    name: "Classic Denim Jacket",
    price: 78,
    category: "men",
    image: "/Denim-Jacket1.jpg",
    image_gallery: [
      "/Denim-Jacket2.jpg",
      "/Denim-Jacket3.jpg",
      "/Denim-Jacket4.jpg",
      "/Denim-Jacket5.jpg",
    ],
    shortDescription: "Timeless denim jacket with button closure",
    fullDescription:
      "A classic denim jacket crafted from durable cotton denim. Designed with button closure, chest pockets, and a regular fit, making it a versatile wardrobe essential.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    isNew: false,
  },
  {
    id: "m035",
    name: "Sleeveless Puffer Vest",
    price: 70,
    category: "men",
    image: "/Puffer-Vest1.jpg",
    image_gallery: [
      "/Puffer-Vest2.jpg",
      "/Puffer-Vest3.jpg",
      "/Puffer-Vest4.jpg",
      "/Puffer-Vest5.jpg",
    ],
    shortDescription: "Lightweight insulated vest for layering",
    fullDescription:
      "This sleeveless puffer vest is insulated with synthetic padding to keep you warm without extra bulk. Perfect for layering over shirts or sweaters in transitional weather.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    isNew: true,
  },
  {
    id: "m036",
    name: "Casual Cargo Shorts",
    price: 37,
    category: "men",
    image: "/Cargo-Shorts1.jpg",
    image_gallery: [
      "/Cargo-Shorts2.jpg",
      "/Cargo-Shorts3.jpg",
      "/Cargo-Shorts4.jpg",
      "/Cargo-Shorts5.jpg",
      "/Cargo-Shorts6.jpg",
    ],
    shortDescription: "Durable cargo shorts with multiple pockets",
    fullDescription:
      "These casual cargo shorts are designed with multiple utility pockets, button closure, and a relaxed fit. Made from breathable cotton fabric for everyday comfort.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "m037",
    name: "Wool Blend Overcoat",
    price: 125,
    category: "men",
    image: "/Wool-Overcoat1.jpg",
    image_gallery: [
      "/Wool-Overcoat2.jpg",
      "/Wool-Overcoat3.jpg",
      "/Wool-Overcoat4.jpg",
      "/Wool-Overcoat5.jpg",
      "/Wool-Overcoat6.jpg",
    ],
    shortDescription: "Elegant wool blend overcoat with tailored fit",
    fullDescription:
      "This wool blend overcoat is designed for warmth and style. Featuring a tailored fit, button front, and inner lining, it’s suitable for both formal and casual occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "m038",
    name: "Cotton Lounge Pants",
    price: 29,
    category: "men",
    image: "/Lounge-Pants1.jpg",
    image_gallery: [
      "/Lounge-Pants2.jpg",
      "/Lounge-Pants3.jpg",
      "/Lounge-Pants4.jpg",
      "/Lounge-Pants5.jpg",
      "/Lounge-Pants6.jpg",
      "/Lounge-Pants7.jpg",
    ],
    shortDescription: "Comfortable cotton lounge pants for home wear",
    fullDescription:
      "Made from soft cotton jersey, these lounge pants are lightweight and breathable. Featuring an elastic waistband with drawstring for comfort during relaxation or sleep.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    isNew: false,
  },
  {
    id: "m039",
    name: "Longline Parka Jacket",
    price: 110,
    category: "men",
    image: "/Parka-Jacket1.jpg",
    image_gallery: [
      "/Parka-Jacket2.jpg",
      "/Parka-Jacket3.jpg",
      "/Parka-Jacket4.jpg",
      "/Parka-Jacket5.jpg",
      "/Parka-Jacket6.jpg",
    ],
    shortDescription: "Warm parka jacket with hood and extended length",
    fullDescription:
      "This longline parka jacket is insulated for warmth and features a detachable hood. Designed with a zip and button closure for reliable cold-weather protection.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    isNew: true,
  },
  {
    id: "m040",
    name: "Casual Knit Beanie",
    price: 18,
    category: "men",
    image: "/Knit-Beanie1.jpg",
    image_gallery: [
      "/Knit-Beanie2.jpg",
      "/Knit-Beanie3.jpg",
      "/Knit-Beanie4.jpg",
      "/Knit-Beanie5.jpg",
      "/Knit-Beanie6.jpg",
    ],
    shortDescription: "Soft knit beanie for everyday wear",
    fullDescription:
      "This casual knit beanie is crafted from soft acrylic yarn to provide warmth and comfort. Its minimalist design makes it a versatile accessory for winter outfits.",
    sizes: ["One Size"],
    rating: 4.5,
    isNew: false,
  },





  // Women's Collection
  {
    id: "w001",
    name: "Elegant Silk Blouse",
    price: 159,
    category: "women",
    image: "/elegant-silk-blouse.png",
    shortDescription: "Luxurious silk blouse with timeless American elegance",
    fullDescription:
      "This elegant silk blouse is crafted from 100% mulberry silk with a lustrous finish. Features a classic collar, button-front closure, and relaxed fit. Perfect for professional or formal occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "w002",
    name: "High-Waisted Skinny Jeans",
    price: 145,
    category: "women",
    image: "/womens-high-waisted-skinny-jeans.png",
    shortDescription: "Premium American denim in a flattering high-waisted cut",
    fullDescription:
      "These high-waisted skinny jeans are made from premium American denim with stretch for comfort and fit. Features a flattering high-rise waist, classic five-pocket styling, and ankle length.",
    sizes: ["24", "26", "28", "30", "32", "34"],
    rating: 4.6,
  },
  {
    id: "w003",
    name: "Cashmere Cardigan Sweater",
    price: 289,
    category: "women",
    image: "/luxury-cashmere-cardigan.png",
    shortDescription: "Luxurious cashmere cardigan for sophisticated style",
    fullDescription:
      "Indulge in luxury with this 100% cashmere cardigan. Features a classic button-front design, ribbed trim, and relaxed fit. Perfect for layering and available in multiple sophisticated colors.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
  },
  {
    id: "w004",
    name: "Floral Summer Dress",
    price: 119,
    category: "women",
    image: "/floral-summer-dress.png",
    shortDescription: "Breezy floral dress perfect for warm weather",
    fullDescription:
      "This charming floral dress features a feminine silhouette with a fitted bodice and flowing skirt. Made from lightweight cotton blend with beautiful floral print. Perfect for summer occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w005",
    name: "Alabama Hat - Flat Bill - Navy Camo / Black - Laser Mesh",
    price: 95,
    category: "men",
    image: "/ProductFeatureIconsALL4.png?height=400&width=400",
    image_gallery: [
      "/ProductFeatureIconsALL1.png?height=400&width=400",
      "/ProductFeatureIconsALL2.png?height=400&width=400",
      "/ProductFeatureIconsALL3.png?height=400&width=400",
      "/ProductFeatureIconsALL4.png?height=400&width=400",
      "/ProductFeatureIconsALL2.png?height=400&width=400",
    ],
    shortDescription: "High-performance leggings for active lifestyle",
    fullDescription:
      "These performance leggings feature four-way stretch fabric, moisture-wicking technology, and a high-waisted design for support. Perfect for yoga, running, or casual wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "w006",
    name: "Classic White Sneakers",
    price: 179,
    category: "women",
    image: "/White-Sneakers1.jpg",
    image_gallery: [
      "/White-Sneakers2.png",
      "/White-Sneakers1.jpg",
      "/White-Sneakers3.jpg",
      "/White-Sneakers4.jpg",
    ],
    shortDescription: "Timeless white sneakers with American craftsmanship",
    fullDescription:
      "These classic white sneakers combine timeless style with modern comfort. Features premium leather upper, cushioned sole, and durable construction. Perfect for casual everyday wear.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w007",
    name: "Women’s Oversized Long Sleeve Basic Crewneck Top",
    price: 179,
    category: "women",
    image: "/Sleeve-Crewneck2.jpg",
    image_gallery: [
      "/Sleeve-Crewneck1.jpg",
      "/Sleeve-Crewneck2.jpg",
      "/Sleeve-Crewneck3.jpg",
      "/Sleeve-Crewneck4.jpg",
      "/Sleeve-Crewneck5.jpg",
    ],
    shortDescription: "Soft oversized crewneck long sleeve top for casual and seasonal wear",
    fullDescription:
      "This women’s oversized long sleeve top features a classic crewneck and a relaxed silhouette for all-day comfort. Made from soft, breathable fabric, it’s ideal for fall layering, casual outings, or light workouts, bringing both comfort and effortless style.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w008",
    name: "Women’s Summer Square Neck T-Shirt with Ruffle Sleeves",
    price: 179,
    category: "women",
    image: "/Ruffle-Sleeves2.jpg",
    image_gallery: [
      "/Ruffle-Sleeves1.jpg",
      "/Ruffle-Sleeves2.jpg",
      "/Ruffle-Sleeves3.jpg",
      "/Ruffle-Sleeves4.jpg",
    ],
    shortDescription: "Lightweight square neck t-shirt with feminine ruffle sleeves for summer",
    fullDescription:
      "This women’s summer t-shirt features a stylish square neckline and delicate ruffle trim sleeves for a feminine touch. Crafted from soft, breathable fabric, it offers comfort and charm, making it perfect for casual outings, warm-weather events, or everyday wear.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w009",
    name: "Women’s Asymmetrical Neck Short Sleeve Tunic Top",
    price: 179,
    category: "women",
    image: "/Short Sleeve2.jpg",
    image_gallery: [
      "/Short Sleeve2.jpg",
      "/Short Sleeve1.jpg",
      "/Short Sleeve3.jpg",
      "/Short Sleeve4.jpg",
    ],
    shortDescription: "Lightweight short sleeve tunic with asymmetrical neckline and button detail",
    fullDescription:
      "This women’s tunic top features an elegant asymmetrical neckline and decorative button accents for a modern touch. Made from lightweight, breathable fabric, it offers comfort and style, making it ideal for summer days, casual gatherings, or dressy casual occasions.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w010",
    name: "Women’s Casual Short Sleeve Scoop Neck T-Shirt Dress with Pockets",
    price: 179,
    category: "women",
    // image: "/T-Shirt-Dress4.jpg",
    image: "/T-Shirt-Dress1.jpg",
    image_gallery: [
      "/T-Shirt-Dress1.jpg",
      "/T-Shirt-Dress2.jpg",
      "/T-Shirt-Dress3.jpg",
      "/T-Shirt-Dress4.jpg",
    ],
    shortDescription: "Comfortable scoop neck short sleeve t-shirt dress with side pockets",
    fullDescription:
      "This women’s casual t-shirt dress features a flattering scoop neckline, short sleeves, and convenient side pockets. Made from soft, breathable fabric, it’s perfect for beach outings, summer strolls, or relaxed everyday wear.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w011",
    name: "Women’s High-Waisted Wide Leg Stretch Denim Jeans",
    price: 179,
    category: "women",
    image: "/Denim Jeans5.jpg",
    image_gallery: [
      "/Denim Jeans1.jpg",
      "/Denim Jeans2.jpg",
      "/Denim Jeans3.jpg",
      "/Denim Jeans4.jpg",
      "/Denim Jeans5.jpg",
    ],
    shortDescription: "Stylish high-waisted wide leg jeans with raw hem and stretch fabric",
    fullDescription:
      "These women’s high-waisted wide leg jeans combine comfort and style with stretchy denim fabric and a trendy raw hem finish. Designed for a flattering fit and versatile wear, perfect for casual outings or dressing up your look.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w012",
    name: "Women’s V-Neck Short Sleeve Floral Mesh Tunic Blouse",
    price: 179,
    category: "women",
    image: "/Mesh Tunic Blouse4.jpg",
    image_gallery: [
      "/Mesh Tunic Blouse1.jpg",
      "/Mesh Tunic Blouse2.jpg",
      "/Mesh Tunic Blouse3.jpg",
      "/Mesh Tunic Blouse4.jpg",
    ],
    shortDescription: "Lightweight floral mesh tunic with double-layer design and V-neck",
    fullDescription:
      "This women’s tunic blouse features a flattering V-neck and short sleeves, crafted with a delicate double-layer floral mesh fabric. Perfect for layering or wearing alone, it combines elegance and comfort for casual or dressy occasions.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4.6,
  },
  {
    id: "w013",
    name: "Women’s Casual Linen Button-Up Shirt",
    price: 199,
    category: "women",
    image: "/Linen-Shirt4.jpg",
    image_gallery: [
      "/Linen-Shirt1.jpg",
      "/Linen-Shirt2.jpg",
      "/Linen-Shirt3.jpg",
      "/Linen-Shirt4.jpg",
    ],
    shortDescription: "Breathable linen shirt with button-up front and relaxed fit",
    fullDescription:
      "This women’s casual shirt is made from lightweight linen, designed with a button-up front and long sleeves. Perfect for warm weather, it offers a relaxed fit that ensures comfort and style throughout the day.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w014",
    name: "Women’s High-Waisted Skinny Jeans",
    price: 299,
    category: "women",
    image: "/Skinny-Jeans4.jpg",
    image_gallery: [
      "/Skinny-Jeans1.jpg",
      "/Skinny-Jeans2.jpg",
      "/Skinny-Jeans3.jpg",
      "/Skinny-Jeans4.jpg",
      "/Skinny-Jeans5.jpg",
    ],
    shortDescription: "Stretchy high-waisted skinny jeans with classic 5-pocket design",
    fullDescription:
      "These women’s high-waisted skinny jeans are crafted with premium stretch denim for comfort and flexibility. Featuring a flattering fit and versatile wash, they’re a wardrobe essential for both casual and dressy looks.",
    sizes: ["24", "25", "26", "27", "28", "29", "30"],
    rating: 4.7,
  },
  {
    id: "w015",
    name: "Women’s Oversized Knit Sweater",
    price: 259,
    category: "women",
    image: "/Knit-Sweater4.jpg",
    image_gallery: [
      "/Knit-Sweater2.jpg",
      "/Knit-Sweater3.jpg",
      "/Knit-Sweater4.jpg",
      "/Knit-Sweater5.jpg",
      "/Knit-Sweater6.jpg",
      "/Knit-Sweater1.jpg",

    ],
    shortDescription: "Soft oversized knit sweater with ribbed hem and cuffs",
    fullDescription:
      "This oversized knit sweater offers a cozy, relaxed silhouette perfect for layering. With ribbed cuffs and hem, it delivers both warmth and effortless style for cooler days.",
    sizes: ["S", "M", "L"],
    rating: 4.8,
  },
  {
    id: "w016",
    name: "Women’s Pleated Midi Skirt",
    price: 229,
    category: "women",
    image: "/Pleated-Skirt4.jpg",
    image_gallery: [
      "/Pleated-Skirt1.jpg",
      "/Pleated-Skirt2.jpg",
      "/Pleated-Skirt3.jpg",
      "/Pleated-Skirt4.jpg",
    ],
    shortDescription: "Chic pleated midi skirt with elastic waistband",
    fullDescription:
      "This pleated midi skirt features a flowy silhouette with an elastic waistband for all-day comfort. A versatile piece that can be styled with blouses, sweaters, or t-shirts for both casual and elegant looks.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "w017",
    name: "Women’s Classic Blazer Jacket",
    price: 349,
    category: "women",
    image: "/Blazer-Jacket4.jpg",
    image_gallery: [
      "/Blazer-Jacket1.jpg",
      "/Blazer-Jacket2.jpg",
      "/Blazer-Jacket3.jpg",
      "/Blazer-Jacket4.jpg",
      "/Blazer-Jacket5.jpg",
      "/Blazer-Jacket6.jpg",
    ],
    shortDescription: "Tailored blazer jacket with notched lapel and front pockets",
    fullDescription:
      "This women’s blazer jacket offers a timeless tailored fit with a notched lapel and functional pockets. Perfect for office wear or layering casually, it adds a polished touch to any outfit.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "w018",
    name: "Women’s Summer Floral Maxi Dress",
    price: 279,
    category: "women",
    image: "/Floral-Maxi-Dress4.jpg",
    image_gallery: [
      "/Floral-Maxi-Dress1.jpg",
      "/Floral-Maxi-Dress2.jpg",
      "/Floral-Maxi-Dress3.jpg",
      "/Floral-Maxi-Dress4.jpg",
      "/Floral-Maxi-Dress5.jpg",
      "/Floral-Maxi-Dress6.jpg",
      "/Floral-Maxi-Dress7.jpg",
    ],
    shortDescription: "Lightweight floral print maxi dress with adjustable straps",
    fullDescription:
      "This maxi dress features a vibrant floral print, a flattering V-neckline, and adjustable straps. Perfect for summer days or vacation, it offers a breezy silhouette with effortless charm.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w019",
    name: "Women’s Faux Leather Biker Jacket",
    price: 399,
    category: "women",
    image: "/Biker-Jacket4.jpg",
    image_gallery: [
      "/Biker-Jacket1.jpg",
      "/Biker-Jacket2.jpg",
      "/Biker-Jacket3.jpg",
      "/Biker-Jacket4.jpg",
      "/Biker-Jacket5.jpg",
    ],
    shortDescription: "Edgy faux leather biker jacket with zipper details",
    fullDescription:
      "This biker jacket is crafted from high-quality faux leather with moto-inspired zipper details. Stylish and versatile, it’s the perfect layering piece to add an edgy vibe to your outfit.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
  },
  {
    id: "w020",
    name: "Women’s Cotton Graphic T-Shirt",
    price: 149,
    category: "women",
    image: "/Graphic-Tee4.jpg",
    image_gallery: [
      "/Graphic-Tee1.jpg",
      "/Graphic-Tee2.jpg",
      "/Graphic-Tee3.jpg",
      "/Graphic-Tee4.jpg",
    ],
    shortDescription: "Casual cotton graphic tee with relaxed fit",
    fullDescription:
      "This cotton T-shirt features a stylish graphic print and a relaxed silhouette. A comfortable everyday essential that pairs easily with jeans, shorts, or skirts for a casual look.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
  },
  {
    id: "w021",
    name: "Women’s Satin Slip Dress",
    price: 329,
    category: "women",
    image: "/Satin-Dress4.jpg",
    image_gallery: [
      "/Satin-Dress1.jpg",
      "/Satin-Dress2.jpg",
      "/Satin-Dress3.jpg",
      "/Satin-Dress4.jpg",
      "/Satin-Dress5.jpg",
    ],
    shortDescription: "Elegant satin slip dress with spaghetti straps",
    fullDescription:
      "This satin slip dress features a silky smooth texture and minimalist design with spaghetti straps. Perfect for parties, evenings out, or layering with a blazer for a chic look.",
    sizes: ["S", "M", "L"],
    rating: 4.6,
  },
  {
    id: "w022",
    name: "Women’s Hooded Puffer Jacket",
    price: 459,
    category: "women",
    image: "/Puffer-Jacket4.webp",
    image_gallery: [
      "/Puffer-Jacket1.webp",
      "/Puffer-Jacket2.webp",
      "/Puffer-Jacket3.webp",
      "/Puffer-Jacket4.webp",
      "/Puffer-Jacket5.webp",
      "/Puffer-Jacket6.webp",
      "/Puffer-Jacket7.webp",
      "/Puffer-Jacket8.webp",
    ],
    shortDescription: "Warm puffer jacket with detachable hood",
    fullDescription:
      "This hooded puffer jacket is designed for warmth and comfort with a quilted finish. Featuring a detachable hood and zippered pockets, it’s ideal for winter layering while staying stylish.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "w023",
    name: "Women’s Cotton Crewneck T-Shirt",
    price: 149,
    category: "women",
    image: "/Cotton-Tee4.jpg",
    image_gallery: [
      "/Cotton-Tee1.jpg",
      "/Cotton-Tee2.jpg",
      "/Cotton-Tee3.jpg",
      "/Cotton-Tee4.jpg",
      "/Cotton-Tee5.jpg",
    ],
    shortDescription: "Basic cotton crewneck tee with soft touch",
    fullDescription:
      "This women’s T-shirt is made from breathable cotton fabric, featuring a classic crew neckline and relaxed fit. A versatile wardrobe essential for everyday wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w024",
    name: "Women’s Casual Jogger Pants",
    price: 229,
    category: "women",
    image: "/Casual-Joggers4.jpg",
    image_gallery: [
      "/Casual-Joggers1.jpg",
      "/Casual-Joggers2.jpg",
      "/Casual-Joggers3.jpg",
      "/Casual-Joggers4.jpg",
      "/Casual-Joggers5.jpg",
      "/Casual-Joggers6.jpg",
    ],
    shortDescription: "Comfortable jogger pants with elastic waist",
    fullDescription:
      "These jogger pants are crafted from soft cotton blend with an elastic waistband and ankle cuffs. Perfect for lounging, workouts, or casual outings.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "w025",
    name: "Women’s Denim Jacket",
    price: 279,
    category: "women",
    image: "/Denim-Jacket4.jpg",
    image_gallery: [
      "/Denim-Jacket1.jpg",
      "/Denim-Jacket2.jpg",
      "/Denim-Jacket3.jpg",
      "/Denim-Jacket4.jpg",
      "/Denim-Jacket5.jpg",
    ],
    shortDescription: "Classic denim jacket with button-up front",
    fullDescription:
      "This denim jacket is a timeless outerwear piece with button-up front, chest pockets, and a relaxed fit. Ideal for layering over dresses, tees, or sweaters.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "w026",
    name: "Women’s Pleated Summer Dress",
    price: 249,
    category: "women",
    image: "/Pleated-Summer-Dress4.jpg",
    image_gallery: [
      "/Pleated-Summer-Dress1.jpg",
      "/Pleated-Summer-Dress2.jpg",
      "/Pleated-Summer-Dress3.jpg",
      "/Pleated-Summer-Dress4.jpg",
      "/Pleated-Summer-Dress5.jpg",
      "/Pleated-Summer-Dress6.jpg",
    ],
    shortDescription: "Lightweight pleated dress for summer days",
    fullDescription:
      "This sleeveless pleated summer dress is made from breathable fabric, featuring a flowy silhouette and adjustable waist tie. Perfect for casual and semi-formal occasions.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "w027",
    name: "Women’s Ribbed Knit Tank Top",
    price: 139,
    category: "women",
    image: "/Ribbed-Tank4.jpg",
    image_gallery: [
      "/Ribbed-Tank1.jpg",
      "/Ribbed-Tank2.jpg",
      "/Ribbed-Tank3.jpg",
      "/Ribbed-Tank4.jpg",
      "/Ribbed-Tank5.jpg",
    ],
    shortDescription: "Fitted ribbed knit tank top with scoop neck",
    fullDescription:
      "This ribbed knit tank top offers a slim fit with a scoop neckline. Ideal for layering under jackets or pairing with skirts and jeans.",
    sizes: ["S", "M", "L"],
    rating: 4.4,
  },
  {
    id: "w028",
    name: "Women’s Relaxed Fit Hoodie",
    price: 259,
    category: "women",
    image: "/Relaxed-Hoodie4.jpg",
    image_gallery: [
      "/Relaxed-Hoodie1.jpg",
      "/Relaxed-Hoodie2.jpg",
      "/Relaxed-Hoodie3.jpg",
      "/Relaxed-Hoodie4.jpg",
      "/Relaxed-Hoodie5.jpg",
      "/Relaxed-Hoodie6.jpg",
      "/Relaxed-Hoodie7.jpg",
    ],
    shortDescription: "Casual hoodie with relaxed fit and front pocket",
    fullDescription:
      "This hoodie is designed with a relaxed fit, kangaroo pocket, and drawstring hood. Made from soft fleece fabric for comfort in cooler weather.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
  },
  {
    id: "w029",
    name: "Women’s A-Line Midi Skirt",
    price: 219,
    category: "women",
    image: "/Aline-Midi-Skirt4.jpg",
    image_gallery: [
      "/Aline-Midi-Skirt1.jpg",
      "/Aline-Midi-Skirt2.jpg",
      "/Aline-Midi-Skirt3.jpg",
      "/Aline-Midi-Skirt4.jpg",
    ],
    shortDescription: "Classic A-line skirt with comfortable waistband",
    fullDescription:
      "This midi skirt features an A-line cut that flatters the figure, designed with a comfortable elastic waistband. A versatile piece for both casual and dressy outfits.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w030",
    name: "Women’s Long Sleeve Blouse",
    price: 189,
    category: "women",
    image: "/Long-Sleeve-Blouse4.jpg",
    image_gallery: [
      "/Long-Sleeve-Blouse1.jpg",
      "/Long-Sleeve-Blouse2.jpg",
      "/Long-Sleeve-Blouse3.jpg",
      "/Long-Sleeve-Blouse4.jpg",
      "/Long-Sleeve-Blouse5.jpg",
    ],
    shortDescription: "Lightweight blouse with buttoned cuffs",
    fullDescription:
      "This long sleeve blouse is made from breathable fabric, designed with buttoned cuffs and a relaxed silhouette. Perfect for office or casual wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "w031",
    name: "Women’s Wide-Leg Pants",
    price: 239,
    category: "women",
    image: "/Wide-Leg-Pants4.jpg",
    image_gallery: [
      "/Wide-Leg-Pants1.jpg",
      "/Wide-Leg-Pants2.jpg",
      "/Wide-Leg-Pants3.jpg",
      "/Wide-Leg-Pants4.jpg",
      "/Wide-Leg-Pants5.jpg",
    ],
    shortDescription: "Relaxed wide-leg pants with elastic waist",
    fullDescription:
      "These wide-leg pants are flowy and comfortable, designed with an elastic waistband and side pockets. A stylish option for casual and work outfits.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
  },
  {
    id: "w032",
    name: "Women’s Lightweight Cardigan",
    price: 199,
    category: "women",
    image: "/Lightweight-Cardigan4.jpg",
    image_gallery: [
      "/Lightweight-Cardigan1.jpg",
      "/Lightweight-Cardigan2.jpg",
      "/Lightweight-Cardigan3.jpg",
      "/Lightweight-Cardigan4.jpg",
      "/Lightweight-Cardigan5.jpg",
    ],
    shortDescription: "Open-front cardigan with soft knit fabric",
    fullDescription:
      "This cardigan is made from soft lightweight knit, designed with an open front and long sleeves. Perfect for layering over dresses or tops.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
  },
  {
    id: "w033",
    name: "Floral Print Summer Dress",
    price: 58,
    category: "women",
    image: "/Floral-Dress1.jpg",
    image_gallery: [
      "/Floral-Dress2.jpg",
      "/Floral-Dress3.jpg",
      "/Floral-Dress4.jpg",
      "/Floral-Dress5.jpg",
      "/Floral-Dress6.jpg",
    ],
    shortDescription: "Lightweight summer dress with floral pattern",
    fullDescription:
      "This floral print summer dress is crafted from breathable fabric with a flowy silhouette. Designed with a V-neckline and short sleeves, it’s perfect for warm weather outings.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "w034",
    name: "High-Waisted Wide Leg Pants",
    price: 49,
    category: "women",
    image: "/WideLeg-Pants1.jpg",
    image_gallery: [
      "/WideLeg-Pants2.jpg",
      "/WideLeg-Pants3.jpg",
      "/WideLeg-Pants4.jpg",
      "/WideLeg-Pants5.jpg",
    ],
    shortDescription: "Elegant wide leg pants with high-rise waist",
    fullDescription:
      "These high-waisted wide leg pants offer a flattering silhouette with a comfortable fit. Made from lightweight woven fabric, they are ideal for both office wear and casual styling.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    isNew: false,
  },
  {
    id: "w035",
    name: "Sleeveless Ribbed Tank Top",
    price: 22,
    category: "women",
    image: "/Ribbed-TankTop1.jpg",
    image_gallery: [
      "/Ribbed-TankTop2.jpg",
      "/Ribbed-TankTop3.jpg",
      "/Ribbed-TankTop4.jpg",
      "/Ribbed-TankTop5.jpg",
    ],
    shortDescription: "Stretch ribbed tank top with scoop neck",
    fullDescription:
      "This sleeveless ribbed tank top is made from stretch cotton for a slim fit. Designed with a scoop neckline, it’s a versatile layering piece for everyday wear.",
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    isNew: true,
  },
  {
    id: "w036",
    name: "Pleated Midi Skirt",
    price: 54,
    category: "women",
    image: "/Pleated-Skirt1.jpg",
    image_gallery: [
      "/Pleated-Skirt2.jpg",
      "/Pleated-Skirt3.jpg",
      "/Pleated-Skirt4.jpg",
      "/Pleated-Skirt5.jpg",
    ],
    shortDescription: "Flowy pleated skirt with elastic waistband",
    fullDescription:
      "A classic pleated midi skirt with a flowy design that moves gracefully. Featuring an elastic waistband for comfort, this skirt pairs well with blouses or knit tops.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    isNew: false,
  },
  {
    id: "w037",
    name: "Wrap Front Blouse",
    price: 39,
    category: "women",
    image: "/Wrap-Blouse1.jpg",
    image_gallery: [
      "/Wrap-Blouse2.jpg",
      "/Wrap-Blouse3.jpg",
      "/Wrap-Blouse4.jpg",
      "/Wrap-Blouse5.jpg",
    ],
    shortDescription: "Chic blouse with wrap front detail",
    fullDescription:
      "This wrap front blouse is crafted from lightweight woven fabric, featuring a flattering V-neckline and adjustable tie waist. Ideal for both office and casual looks.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    isNew: true,
  },
  {
    id: "w038",
    name: "Knitted Cropped Sweater",
    price: 42,
    category: "women",
    image: "/Cropped-Sweater1.jpg",
    image_gallery: [
      "/Cropped-Sweater2.jpg",
      "/Cropped-Sweater3.jpg",
      "/Cropped-Sweater4.jpg",
      "/Cropped-Sweater5.jpg",
      "/Cropped-Sweater6.jpg",
    ],
    shortDescription: "Cozy cropped sweater with long sleeves",
    fullDescription:
      "This knitted cropped sweater is designed with a relaxed fit and ribbed hem. Perfect for layering over dresses or pairing with high-waisted bottoms.",
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    isNew: false,
  },
  {
    id: "w039",
    name: "Denim A-Line Skirt",
    price: 46,
    category: "women",
    image: "/Denim-Skirt1.jpg",
    image_gallery: [
      "/Denim-Skirt2.jpg",
      "/Denim-Skirt3.jpg",
      "/Denim-Skirt4.jpg",
      "/Denim-Skirt5.jpg",
      "/Denim-Skirt6.jpg",
    ],
    shortDescription: "Classic A-line denim skirt with front button closure",
    fullDescription:
      "This denim A-line skirt features a high waist, front button closure, and side pockets. A timeless piece that pairs effortlessly with casual tops or sweaters.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "w040",
    name: "Long Sleeve Maxi Dress",
    price: 72,
    category: "women",
    image: "/Maxi-Dress1.jpg",
    image_gallery: [
      "/Maxi-Dress2.jpg",
      "/Maxi-Dress3.jpg",
      "/Maxi-Dress4.jpg",
      "/Maxi-Dress5.jpg",
      "/Maxi-Dress6.jpg",
    ],
    shortDescription: "Elegant maxi dress with long sleeves",
    fullDescription:
      "This long sleeve maxi dress is made from soft flowing fabric for a feminine silhouette. Designed with a round neckline and side slit for added elegance.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    isNew: false,
  },
  {
    id: "w041",
    name: "High-Neck Knitted Top",
    price: 36,
    category: "women",
    image: "/Knitted-Top1.jpg",
    image_gallery: [
      "/Knitted-Top2.jpg",
      "/Knitted-Top3.jpg",
      "/Knitted-Top4.jpg",
      "/Knitted-Top5.jpg",
    ],
    shortDescription: "Fitted knitted top with high neckline",
    fullDescription:
      "This high-neck knitted top is designed with a slim fit, ribbed texture, and stretch fabric for comfort. A versatile piece that can be dressed up or down.",
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    isNew: true,
  },
  {
    id: "w042",
    name: "Faux Leather Biker Jacket",
    price: 89,
    category: "women",
    image: "/Biker-Jacket1.jpg",
    image_gallery: [
      "/Biker-Jacket2.jpg",
      "/Biker-Jacket3.jpg",
      "/Biker-Jacket4.jpg",
      "/Biker-Jacket5.jpg",
    ],
    shortDescription: "Edgy biker jacket made from faux leather",
    fullDescription:
      "This faux leather biker jacket features a zip front, notched lapels, and multiple pockets. A statement outerwear piece that adds edge to any outfit.",
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    isNew: true,
  },

  
  

  // Accessories
  {
    id: "a001",
    name: "Leather Crossbody Bag",
    price: 225,
    category: "accessories",
    image: "/Leather-Crossbody-Bag1.png?height=400&width=400",
    image_gallery: [
      "/Leather-Crossbody-Bag1.png?height=400&width=400",
      "/Leather-Crossbody-Bag2.png?height=400&width=400",
      "/Leather-Crossbody-Bag3.png?height=400&width=400",
      "/Leather-Crossbody-Bag4.png?height=400&width=400",
      // "/Leather-Crossbody-Bag2.png?height=400&width=400",
    ],
    shortDescription: "Handcrafted leather crossbody bag with American craftsmanship",
    fullDescription:
      "This elegant crossbody bag is handcrafted from premium American leather. Features adjustable strap, multiple compartments, and antique brass hardware. Perfect for everyday use or travel.",
    sizes: ["One Size"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "a002",
    name: "Classic Baseball Cap",
    price: 45,
    category: "accessories",
    image: "/Classic-Baseball-Cap2.jpg?height=400&width=400",
    image_gallery: [
      "/Classic-Baseball-Cap1.jpg?height=400&width=400",
      "/Classic-Baseball-Cap2.jpg?height=400&width=400",
      "/Classic-Baseball-Cap3.jpg?height=400&width=400",
      "/Classic-Baseball-Cap4.jpg?height=400&width=400",
      "/Classic-Baseball-Cap1.jpg?height=400&width=400",
    ],
    shortDescription: "Authentic American baseball cap with classic styling",
    fullDescription:
      "This classic baseball cap features authentic American styling with premium cotton construction. Adjustable back strap and curved brim for comfortable fit and sun protection.",
    sizes: ["One Size"],
    rating: 4.4,
  },
  {
    id: "a003",
    name: "Silk Scarf",
    price: 89,
    category: "accessories",
    image: "/Silk-Scarf1.jpg?height=400&width=400",
    image_gallery: [
      "/Silk-Scarf1.jpg?height=400&width=400",
      "/Silk-Scarf2.jpg?height=400&width=400",
      "/Silk-Scarf3.jpg?height=400&width=400",
      "/Silk-Scarf4.jpg?height=400&width=400",
      "/Silk-Scarf1.jpg?height=400&width=400",
    ],
    shortDescription: "Luxurious silk scarf with elegant American design",
    fullDescription:
      "This luxurious silk scarf is made from 100% mulberry silk with beautiful American-inspired prints. Perfect for adding elegance to any outfit or as a hair accessory.",
    sizes: ["One Size"],
    rating: 4.7,
  },
  {
    id: "a004",
    name: "Leather Belt",
    price: 125,
    category: "accessories",
    image: "/Leather-Belt1.jpg?height=400&width=400",
    image_gallery: [
      "/Leather-Belt1.jpg?height=400&width=400",
      "/Leather-Belt2.jpg?height=400&width=400",
      "/Leather-Belt3.jpg?height=400&width=400",
      "/Leather-Belt4.jpg?height=400&width=400",
      "/Leather-Belt1.jpg?height=400&width=400",
    ],
    shortDescription: "Premium leather belt with classic American craftsmanship",
    fullDescription:
      "This premium leather belt is crafted from full-grain American leather with solid brass buckle. Features classic stitching and available in multiple sizes for the perfect fit.",
    sizes: ["30", "32", "34", "36", "38", "40"],
    rating: 4.6,
  },
  // {
  //   id: "a005",
  //   name: "Belt Emerald",
  //   price: 159,
  //   category: "accessories",
  //   image: "/Belt-Emerald1.jpg?height=400&width=400",
  //   image_gallery: [
  //     "/Belt-Emerald1.jpg?height=400&width=400",
  //     "/Belt-Emerald2.jpg?height=400&width=400",
  //     "/Belt-Emerald3.jpg?height=400&width=400",
  //     "/Belt-Emerald4.jpg?height=400&width=400",
  //     "/Belt-Emerald1.jpg?height=400&width=400",
  //   ],
  //   shortDescription: "Elegant emerald-green leather belt with refined craftsmanship",
  //   fullDescription:
  //     "This elegant belt is made from high-quality genuine leather dyed in a rich emerald hue, paired with a durable matte silver buckle. Showcases meticulous stitching and adjustable sizing, perfect for adding a sophisticated touch to any outfit.",
  //   sizes: ["One Size"],
  //   rating: 4.5,
  // },
  {
    id: "a006",
    name: "Violet Magenta Ombre Silk Chiffon Shawl for women",
    price: 75,
    category: "accessories",
    image: "/Violet-Magenta-Ombre3.jpg",
    image_gallery: [
      "/Violet-Magenta-Ombre1.jpg",
      "/Violet-Magenta-Ombre2.jpg",
      "/Violet-Magenta-Ombre3.jpg",
      "/Violet-Magenta-Ombre4.jpg",
      "/Violet-Magenta-Ombre5.jpeg",
    ],
    shortDescription: "Durable canvas tote bag made in America",
    fullDescription:
      "This sturdy canvas tote bag is made from heavy-duty American cotton canvas. Features reinforced handles, interior pocket, and spacious main compartment. Perfect for shopping or daily use.",
    sizes: ["One Size"],
    rating: 4.3,
  },
  {
    id: "a005",
    name: "Belt Emerald",
    price: 159,
    category: "accessories",
    image: "/Belt-Emerald1.jpg?height=400&width=400",
    image_gallery: [
      "/Belt-Emerald1.jpg?height=400&width=400",
      "/Belt-Emerald2.jpg?height=400&width=400",
      "/Belt-Emerald3.jpg?height=400&width=400",
      "/Belt-Emerald4.jpg?height=400&width=400",
      "/Belt-Emerald1.jpg?height=400&width=400",
    ],
    shortDescription: "Elegant emerald-green leather belt with refined craftsmanship",
    fullDescription:
      "This elegant belt is made from high-quality genuine leather dyed in a rich emerald hue, paired with a durable matte silver buckle. Showcases meticulous stitching and adjustable sizing, perfect for adding a sophisticated touch to any outfit.",
    sizes: ["One Size"],
    rating: 4.5,
  },
  {
    id: "a007",
    name: "Cotton Printed Scarf",
    price: 85,
    category: "accessories",
    image: "/Cotton-Printed-Scarf1.jpg?height=400&width=400",
    image_gallery: [
      "/Cotton-Printed-Scarf1.jpg?height=400&width=400",
      "/Cotton-Printed-Scarf2.jpg?height=400&width=400",
      "/Cotton-Printed-Scarf3.jpg?height=400&width=400",
      "/Cotton-Printed-Scarf4.jpg?height=400&width=400",
    ],
    shortDescription: "Soft cotton scarf with colorful print design",
    fullDescription:
      "This cotton scarf is soft and breathable, decorated with a simple yet stylish print. It can be worn around the neck, as a hair accessory, or tied on a bag.",
    sizes: ["One Size"],
    rating: 4.5,
  },
  {
    id: "a008",
    name: "Fabric Belt with Metal Buckle",
    price: 110,
    category: "accessories",
    image: "/Fabric-Belt1.jpg?height=400&width=400",
    image_gallery: [
      "/Fabric-Belt2.jpg?height=400&width=400",
      "/Fabric-Belt3.jpg?height=400&width=400",
      "/Fabric-Belt4.jpg?height=400&width=400",
      "/Fabric-Belt5.jpg?height=400&width=400",
    ],
    shortDescription: "Durable fabric belt with adjustable buckle",
    fullDescription:
      "This belt is made from sturdy woven fabric, designed with a simple metal buckle for everyday use. Suitable for jeans, shorts, or casual trousers.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
  },
  {
    id: "a009",
    name: "Knitted Winter Beanie",
    price: 120,
    category: "accessories",
    image: "/Knitted-Beanie1.jpg?height=400&width=400",
    image_gallery: [
      "/Knitted-Beanie2.jpg?height=400&width=400",
      "/Knitted-Beanie3.jpg?height=400&width=400",
      "/Knitted-Beanie4.jpg?height=400&width=400",
      "/Knitted-Beanie5.jpg?height=400&width=400",
      "/Knitted-Beanie6.jpg?height=400&width=400",
      "/Knitted-Beanie7.jpg?height=400&width=400",
    ],
    shortDescription: "Warm knitted beanie hat for winter",
    fullDescription:
      "This knitted beanie is soft, stretchable, and designed to keep you warm in colder weather. A casual essential for everyday wear.",
    sizes: ["One Size"],
    rating: 4.7,
  },
  {
    id: "a010",
    name: "Canvas Mini Tote Bag",
    price: 135,
    category: "accessories",
    image: "/Canvas-Mini-Tote1.jpg?height=400&width=400",
    image_gallery: [
      "/Canvas-Mini-Tote1.jpg?height=400&width=400",
      "/Canvas-Mini-Tote2.jpg?height=400&width=400",
      "/Canvas-Mini-Tote3.jpg?height=400&width=400",
      "/Canvas-Mini-Tote4.jpg?height=400&width=400",
      "/Canvas-Mini-Tote5.jpg?height=400&width=400",
      "/Canvas-Mini-Tote6.jpg?height=400&width=400",
    ],
    shortDescription: "Compact canvas tote bag with sturdy handles",
    fullDescription:
      "This mini tote is made from durable canvas with reinforced stitching. Compact yet practical, ideal for carrying daily essentials.",
    sizes: ["One Size"],
    rating: 4.6,
    isNew: true,
  },
  {
    id: "a011",
    name: "Knitted Fingerless Gloves",
    price: 90,
    category: "accessories",
    image: "/Knitted-Fingerless-Gloves1.jpg?height=400&width=400",
    image_gallery: [
      "/Knitted-Fingerless-Gloves2.jpg?height=400&width=400",
      "/Knitted-Fingerless-Gloves3.jpg?height=400&width=400",
      "/Knitted-Fingerless-Gloves4.jpg?height=400&width=400",
      "/Knitted-Fingerless-Gloves5.jpg?height=400&width=400",
      "/Knitted-Fingerless-Gloves6.jpg?height=400&width=400",
      "/Knitted-Fingerless-Gloves7.jpg?height=400&width=400",
    ],
    shortDescription: "Cozy knitted fingerless gloves for everyday wear",
    fullDescription:
      "These fingerless gloves are warm and practical, allowing flexibility for using your phone or working outdoors in chilly weather.",
    sizes: ["S", "M", "L"],
    rating: 4.5,
  },
  {
    id: "a012",
    name: "Striped Cotton Socks (3-Pack)",
    price: 75,
    category: "accessories",
    image: "/Striped-Socks1.jpg?height=400&width=400",
    image_gallery: [
      "/Striped-Socks2.jpg?height=400&width=400",
      "/Striped-Socks3.jpg?height=400&width=400",
      "/Striped-Socks4.jpg?height=400&width=400",
      "/Striped-Socks5.jpg?height=400&width=400",
      "/Striped-Socks6.jpg?height=400&width=400",
      "/Striped-Socks7.jpg?height=400&width=400",
    ],
    shortDescription: "Pack of 3 striped cotton socks, breathable and soft",
    fullDescription:
      "These striped cotton socks come in a set of 3 pairs, featuring breathable fabric and elastic cuffs for all-day comfort.",
    sizes: ["S", "M", "L"],
    rating: 4.4,
  },
  {
    id: "a013",
    name: "Canvas Crossbody Pouch",
    price: 145,
    category: "accessories",
    image: "/Canvas-Crossbody-Pouch1.jpg",
    image_gallery: [
      // "/Canvas-Crossbody-Pouch1.jpg",
      "/Canvas-Crossbody-Pouch2.jpg",
      "/Canvas-Crossbody-Pouch3.jpg",
      "/Canvas-Crossbody-Pouch4.jpg",
      "/Canvas-Crossbody-Pouch5.jpg",
      "/Canvas-Crossbody-Pouch6.jpg",
    ],
    shortDescription: "Compact crossbody pouch made of durable canvas",
    fullDescription:
      "This crossbody pouch is lightweight and convenient for carrying essentials like phone, wallet, and keys. Adjustable strap for comfort.",
    sizes: ["One Size"],
    rating: 4.7,
  },
  {
    id: "a014",
    name: "Elastic Hair Tie Set (6-Pack)",
    price: 70,
    category: "accessories",
    image: "/Hair-Tie-Set1.jpg?height=400&width=400",
    image_gallery: [
      "/Hair-Tie-Set2.jpg?height=400&width=400",
      "/Hair-Tie-Set3.jpg?height=400&width=400",
      "/Hair-Tie-Set4.jpg?height=400&width=400",
      "/Hair-Tie-Set5.jpg?height=400&width=400",
      "/Hair-Tie-Set6.jpg?height=400&width=400",
      "/Hair-Tie-Set7.jpg?height=400&width=400",
    ],
    shortDescription: "Set of 6 elastic hair ties in assorted colors",
    fullDescription:
      "These elastic hair ties are durable, soft, and gentle on hair. The set includes multiple colors, suitable for daily use and styling.",
    sizes: ["One Size"],
    rating: 4.3,
  },
  {
    id: "a015",
    name: "Casual Daypack Backpack",
    price: 220,
    category: "accessories",
    image: "/Casual-Daypack1.jpg?height=400&width=400",
    image_gallery: [
      // "/Casual-Daypack1.jpg?height=400&width=400",
      "/Casual-Daypack2.jpg?height=400&width=400",
      "/Casual-Daypack3.jpg?height=400&width=400",
      "/Casual-Daypack4.jpg?height=400&width=400",
      "/Casual-Daypack5.jpg?height=400&width=400",
      "/Casual-Daypack6.jpg?height=400&width=400",
    ],
    shortDescription: "Lightweight casual backpack for school or work",
    fullDescription:
      "This daypack is practical and lightweight, featuring adjustable straps and multiple compartments. Perfect for students or daily commuters.",
    sizes: ["One Size"],
    rating: 4.8,
    isNew: true,
  },
  {
    id: "a016",
    name: "Casual Baseball Cap",
    price: 110,
    category: "accessories",
    image: "/Casual-Baseball-Cap1.jpg",
    image_gallery: [
      "/Casual-Baseball-Cap1.jpg",
      "/Casual-Baseball-Cap2.jpg",
      "/Casual-Baseball-Cap3.jpg",
      "/Casual-Baseball-Cap4.jpg",
      "/Casual-Baseball-Cap5.jpg",
    ],
    shortDescription: "Classic cotton baseball cap with adjustable strap",
    fullDescription:
      "This casual baseball cap is made from breathable cotton, designed with a curved brim and adjustable strap for a comfortable fit. A simple accessory for everyday wear.",
    sizes: ["One Size"],
    rating: 4.6,
  },
  {
    id: "a017",
    name: "Reusable Cotton Tote Bag",
    price: 95,
    category: "accessories",
    image: "/Reusable-Tote-Bag1.jpg?height=400&width=400",
    image_gallery: [
      "/Reusable-Tote-Bag2.jpg?height=400&width=400",
      "/Reusable-Tote-Bag3.jpg?height=400&width=400",
      "/Reusable-Tote-Bag4.jpg?height=400&width=400",
      "/Reusable-Tote-Bag5.jpg?height=400&width=400",
      "/Reusable-Tote-Bag6.jpg?height=400&width=400",
    ],
    shortDescription: "Eco-friendly cotton tote bag for daily use",
    fullDescription:
      "This reusable tote bag is made from durable cotton canvas. Lightweight yet sturdy, it’s ideal for shopping, school, or casual outings.",
    sizes: ["One Size"],
    rating: 4.5,
  },
  {
    id: "a018",
    name: "Lightweight Infinity Scarf",
    price: 120,
    category: "accessories",
    image: "/Infinity-Scarf1.jpg?height=400&width=400",
    image_gallery: [
      "/Infinity-Scarf1.jpg?height=400&width=400",
      "/Infinity-Scarf2.jpg?height=400&width=400",
      "/Infinity-Scarf3.jpg?height=400&width=400",
      "/Infinity-Scarf4.jpg?height=400&width=400",
    ],
    shortDescription: "Soft infinity scarf for layering and warmth",
    fullDescription:
      "This lightweight infinity scarf is versatile and cozy, designed for layering with casual or semi-formal outfits. Available in neutral colors for easy styling.",
    sizes: ["One Size"],
    rating: 4.6,
  },
  {
    id: "a019",
    name: "Knitted Headband Ear Warmer",
    price: 85,
    category: "accessories",
    image: "/Knitted-Headband1.jpg?height=400&width=400",
    image_gallery: [
      "/Knitted-Headband1.jpg?height=400&width=400",
      "/Knitted-Headband2.jpg?height=400&width=400",
      "/Knitted-Headband3.jpg?height=400&width=400",
      "/Knitted-Headband4.jpg?height=400&width=400",
      "/Knitted-Headband5.jpg?height=400&width=400",
      "/Knitted-Headband6.jpg?height=400&width=400",
    ],
    shortDescription: "Warm knitted headband for cold days",
    fullDescription:
      "This knitted headband doubles as an ear warmer, perfect for chilly weather. Stretchable design ensures comfort and a snug fit.",
    sizes: ["One Size"],
    rating: 4.4,
  },
  {
    id: "a020",
    name: "Casual Sling Bag",
    price: 185,
    category: "accessories",
    image: "/Casual-Sling-Bag1.jpg",
    image_gallery: [
      "/Casual-Sling-Bag1.jpg",
      "/Casual-Sling-Bag2.jpg",
      "/Casual-Sling-Bag3.jpg",
      "/Casual-Sling-Bag4.jpg",
      "/Casual-Sling-Bag5.jpg",
      "/Casual-Sling-Bag6.jpg",
    ],
    shortDescription: "Lightweight sling bag for everyday use",
    fullDescription:
      "This casual sling bag is compact and practical, featuring adjustable straps and multiple compartments for essentials. Great for daily wear or travel.",
    sizes: ["One Size"],
    rating: 4.6,
  },
  {
    id: "a021",
    name: "Cotton Bandana",
    price: 70,
    category: "accessories",
    image: "/Cotton-Bandana1.jpg",
    image_gallery: [
      "/Cotton-Bandana1.jpg",
      "/Cotton-Bandana2.jpg",
      "/Cotton-Bandana3.jpg",
      "/Cotton-Bandana4.jpg",
      "/Cotton-Bandana5.jpg",
      "/Cotton-Bandana6.jpg",
      "/Cotton-Bandana7.jpg",
    ],
    shortDescription: "Versatile cotton bandana with printed design",
    fullDescription:
      "This cotton bandana can be styled in multiple ways: around the neck, as a headband, or tied to a bag. Lightweight and breathable for everyday fashion.",
    sizes: ["One Size"],
    rating: 4.3,
  },
  {
    id: "a022",
    name: "Drawstring Gym Bag",
    price: 130,
    category: "accessories",
    image: "/Drawstring-Gym-Bag1.jpg?height=400&width=400",
    image_gallery: [
      "/Drawstring-Gym-Bag1.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag2.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag3.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag4.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag5.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag6.jpg?height=400&width=400",
      "/Drawstring-Gym-Bag7.jpg?height=400&width=400",
    ],
    shortDescription: "Lightweight drawstring bag for gym or casual use",
    fullDescription:
      "This drawstring bag is lightweight and spacious enough for essentials. Made from durable polyester, ideal for gym sessions, travel, or everyday carry.",
    sizes: ["One Size"],
    rating: 4.5,
  },
  {
    id: "a023",
    name: "Simple Fabric Wristband",
    price: 75,
    category: "accessories",
    image: "/Fabric-Wristband1.jpg?height=400&width=400",
    image_gallery: [
      "/Fabric-Wristband1.jpg?height=400&width=400",
      "/Fabric-Wristband2.jpg?height=400&width=400",
      "/Fabric-Wristband3.jpg?height=400&width=400",
      "/Fabric-Wristband4.jpg?height=400&width=400",
      "/Fabric-Wristband5.jpg?height=400&width=400",
      "/Fabric-Wristband6.jpg?height=400&width=400",
    ],
    shortDescription: "Casual fabric wristband for everyday wear",
    fullDescription:
      "This simple wristband is made from soft woven fabric, lightweight and comfortable. A subtle accessory that can be styled casually.",
    sizes: ["One Size"],
    rating: 4.2,
  },
  {
    id: "a024",
    name: "Canvas Lunch Bag",
    price: 145,
    category: "accessories",
    image: "/Canvas-Lunch-Bag1.jpg",
    image_gallery: [
      "/Canvas-Lunch-Bag1.jpg",
      "/Canvas-Lunch-Bag2.jpg",
      "/Canvas-Lunch-Bag3.jpg",
      "/Canvas-Lunch-Bag4.jpg",
      "/Canvas-Lunch-Bag5.jpg",
    ],
    shortDescription: "Reusable lunch bag made of durable canvas",
    fullDescription:
      "This eco-friendly lunch bag is made from sturdy canvas with insulated lining, keeping food fresh and easy to carry for school or work.",
    sizes: ["One Size"],
    rating: 4.7,
  },
  {
    id: "a025",
    name: "Everyday Backpack",
    price: 210,
    category: "accessories",
    image: "/Everyday-Backpack1.jpeg",
    image_gallery: [
      "/Everyday-Backpack1.jpeg",
      "/Everyday-Backpack2.jpeg",
      "/Everyday-Backpack3.jpeg",
      "/Everyday-Backpack4.jpeg",
      "/Everyday-Backpack5.jpeg",
      "/Everyday-Backpack6.jpeg",
    ],
    shortDescription: "Durable everyday backpack with multiple pockets",
    fullDescription:
      "This backpack is designed for daily use, featuring padded straps, a laptop compartment, and multiple storage pockets. Practical and lightweight for students or commuters.",
    sizes: ["One Size"],
    rating: 4.8,
  }
  
  
  
  
  // {
  //   id: "a006",
  //   name: "Violet Magenta Ombre Silk Chiffon Shawl for women",
  //   price: 75,
  //   category: "accessories",
  //   image: "/Violet-Magenta-Ombre3.jpg",
  //   image_gallery: [
  //     "/Violet-Magenta-Ombre1.jpg",
  //     "/Violet-Magenta-Ombre2.jpg",
  //     "/Violet-Magenta-Ombre3.jpg",
  //     "/Violet-Magenta-Ombre4.jpg",
  //     "/Violet-Magenta-Ombre5.jpeg",
  //   ],
  //   shortDescription: "Durable canvas tote bag made in America",
  //   fullDescription:
  //     "This sturdy canvas tote bag is made from heavy-duty American cotton canvas. Features reinforced handles, interior pocket, and spacious main compartment. Perfect for shopping or daily use.",
  //   sizes: ["One Size"],
  //   rating: 4.3,
  // },
  //test products
  
]
